###
GET http://localhost:4004/odata/v4/emp/Employees

###
POST http://localhost:4004/odata/v4/emp/Employees
Content-Type: application/json

{
    "empId":"1008",
    "empName":"Kiran Kiran",
    "empDesg":"Team Lead",
    "empAdd":"TG",
    "empSalary":"100050",
    "empPos": "U4",
    "toProject": [
                {
                    "PrjCode": "IK001",
                    "PrjName": "IkeaRetail",
                    "PrjDesc": "Retail R"
                }
                ]
}

###
GET  http://localhost:4004/odata/v4/emp/getEmpbyPos(empPos='Temp')